package com.example.potterguide.ui.activity

const val CHAVE_TELA: String = "CHAVE_TELA"
const val CHAVE_PERSONAGEM = "CHAVE_PERSONAGEM"
const val CHAVE_CASA = "CHAVE_CASA"

const val CHAVE_CASA_GRIFINORIA = "GRIFINÓRIA"
const val CHAVE_CASA_SONSERINA = "SONSERINA"
const val CHAVE_CASA_CORVINAL = "CORVINAL"
const val CHAVE_CASA_LUFA_LUFA = "LUFA - LUFA"

const val CHAVE_TODOS_OS_PERSONAGENS = "TODOS OS PERSONAGENS"
const val CHAVE_PERSONAGENS_ALUNOS = "ALUNOS"
const val CHAVE_PERSONAGENS_fUNCIONARIOS = "FUNCIONARIOS"

const val CHAVE_PERSONAGENS_GRIFINORIA = "ALUNOS DE GRIFINÓRIA"
const val CHAVE_PERSONAGENS_SONSERINA = "ALUNOS DE SONSERINA"
const val CHAVE_PERSONAGENS_CORVINAL = "ALUNOS DE CORVINAL"
const val CHAVE_PERSONAGENS_LUFA_LUFA = "ALUNOS DE LUFA - LUFA"